### ISSUE TITLE
This mod may violate the GPL 3.0 license.

### ISSUE THREAD

**Issue by tukasa0001** [EnhancedNetwork/TownofHost-Enhanced#1271] opened 2024-10-27 13:33 UTC
This mod may violate the GPL 3.0 license.

[Section 6-d of the GPL 3.0 license](https://www.gnu.org/licenses/gpl-3.0.html#section6) provides:
> You may convey a covered work in object code form under the terms of sections 4 and 5, provided that you also convey the machine-readable Corresponding Source under the terms of this License, in one of these ways:
> [...]
> - d) Convey the object code by offering access from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge. You need not require recipients to copy the Corresponding Source along with the object code. If the place to copy the object code is a network server, the Corresponding Source may be on a different server (operated by you or a third party) that supports equivalent copying facilities, provided you maintain clear directions next to the object code saying where to find the Corresponding Source. Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.

If you convey the mod binary, you have to offer equivalent access to the mod source, but the API Token needed to build the mod is not provided on GitHub, thus it may violate the GPL.
According to the README, the API Token is available on the Discord server, but that is not "equivalent access" and may violate the GPL in the same way.

**Comment by NikoCat233** [comment] 2024-10-27 14:22
Some time ago, this mod would refuse to start without an API key. However, they have made some changes so that now, even if you don’t provide an API key or input an incorrect one, it will just display a message saying "You cannot connect to the API," and you can still play normally.

**Comment by NikoCat233** [comment] 2024-10-27 14:24
They can simply change the "you need a api key" to "api key is optional to access the api" in readme.

**Comment by Pietrodjaowjao** [comment] 2024-10-27 14:37
@0xDrMoe Add token.env in the project with this content:
"API_TOKEN=REPLACE THIS ONLY IF YOU GOT YOUR OWN API TOKEN"

**Comment by Tommy-XL** [comment] 2024-10-27 14:40
> @0xDrMoe Add token.env in the project with this content: "API_TOKEN=REPLACE THIS ONLY IF YOU GOT YOUR OWN API TOKEN"

This makes sense

**Comment by Tommy-XL** [comment] 2024-10-27 14:43
https://github.com/EnhancedNetwork/TownofHost-Enhanced/pull/1272

**Comment by Hyz-sui** [comment] 2024-10-27 14:46
My understanding is that you MUST publish the resources used to build the binary you publish, **whether buildable or not, without modifying/removing a single character or byte.**
The requirements for "publish" are as described above.
Do you understand about that? @NikoCat233 @Pietrodjaowjao @Tommy-XL

**Comment by NikoCat233** [comment] 2024-10-27 14:53
Typically you dont need to change anything you build
And you dont need to release the resources you used to build

**Comment by Hyz-sui** [comment] 2024-10-27 15:17
As I wrote just above, it doesn't matter whether buildable or not.

**Comment by NikoCat233** [comment] 2024-10-27 15:28
I'm sure they dont need to publish the api backened

**Comment by GianniIta87** [comment] 2024-10-27 18:40
you can edit and delete some files to solve the annoying "You cannot connect to the API" message.
I don't know if I can post the steps here.
Alternatively unpack the original dll file and find the token there

**Comment by 0xDrMoe** [comment] 2024-10-27 19:46
**Legal Compliance Statement**

Town of Host Enhanced (TOHE) Compliance with GPL 3.0 Requirements

The legal team of Town of Host Enhanced (TOHE) hereby affirms that TOHE is in full compliance with the GNU General Public License version 3.0 (GPL 3.0) and remains in good standing under its terms. TOHE’s compliance is based on the following measures, each carefully implemented to uphold and respect the freedoms granted to users under GPL 3.0:

**    1.    Source Code Availability:** TOHE ensures that all source code, including any necessary files required to compile and run the software, is freely and readily available to the public. This includes the complete Corresponding Source, as defined in Section 1 of the GPL, provided alongside any object code distribution.

**    2.    Transparency and Accessibility:** In compliance with Section 6-d of GPL 3.0, TOHE provides unrestricted and equivalent access to the Corresponding Source, so any user receiving the object code can locate, download, and utilize the source code in a straightforward manner. Any elements necessary to configure or customize the mod are provided directly on our GitHub repository or other designated servers, with clear instructions on how to access them.

**    3.    API Key Access Requirements:** While TOHE incorporates an optional API key to enhance connectivity features, this API key is not essential for the base functionality or compilation of the mod, and the mod operates independently without it. Any optional features associated with an API key are fully disclosed, with appropriate placeholders in the code. This ensures users can build and use the program in its entirety, in compliance with GPL requirements, without any dependency on proprietary resources or restricted access.

**    4.    User Freedom and Modification Rights:** Consistent with the GPL 3.0’s philosophy, TOHE allows users to modify, improve, and distribute modified versions of the software freely. All notices, disclaimers, and legal obligations under GPL 3.0 remain intact and prominently available to users, ensuring full awareness of their rights and freedoms under this license.

**    5.    Ongoing Compliance and Review:** TOHE regularly reviews its compliance with GPL 3.0 to maintain good standing and to proactively address any potential concerns regarding transparency, accessibility, or licensing. We are committed to making any adjustments necessary to align with the evolving interpretations of GPL 3.0 and to support the community’s right to access, modify, and share free software.

In conclusion, TOHE is dedicated to respecting and upholding all the requirements and principles of GPL 3.0, and we take every precaution and action necessary to ensure our ongoing compliance. If any user or contributor identifies a concern regarding our compliance with GPL 3.0, we welcome open communication to address it promptly and transparently.

**Comment by 0xDrMoe** [comment] 2024-10-27 19:46
Let me know if you have any questions!

**Comment by miniduikboot** [comment] 2024-10-29 07:54
I have some questions:

1. GPL v3.0 defines “Corresponding Source” as follows:

> The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities.

If I compile this corresponding source, I expect to get a version of TOHE that is functionally equivalent to the version of TOHE that I downloaded from your Github page. However, this is not the case: it is missing access to the API, because no key was included. So the behaviour of the TOHE binary and the TOHE source code is different and therefore the corresponding source does not include all the source code necessary to run the object code.

Please explain why you think it is acceptable to post an incomplete version of the source code.

2. In your statement point 3, you state the following:

> While TOHE incorporates an optional API key to enhance connectivity features, this API key is not essential for the base functionality or compilation of the mod, and the mod operates independently without it. [...] This ensures users can build and use the program in its entirety, in compliance with GPL requirements, without any dependency on proprietary resources or restricted access.

At the time the issue was filed, TOHE did not compile without adding a dummy API key. Therefore the corresponding source can only be considered incomplete. Do you agree that at the time this issue was filed, TOHE did not comply with the GPL?

**Comment by NikoCat233** [comment] 2024-10-29 16:09
Btw it is possible that they remove the release dlls from github and only post in discord.
On discord they can safely claim the dlls arent 100% same with the source and that will be ok i guess.

**Comment by NikoCat233** [comment] 2024-10-29 16:26
@0xDrMoe You can litterly make the public part of api accessible without a api key.
I dont think there can be any use to require others to build with a api key.

**Comment by GianniIta87** [comment] 2024-10-29 16:41
I started modifying mods (for personal and hobby use) with Tohe. I had never used vscode. I managed to get a working mod without using the api key, deleting a file and making 2 small changes. Among other things, I also managed to extract the api key from the original dll file, but since it was not necessary, I immediately trashed it. So I confirm that the api key is not essential to make the mod work

**Comment by GianniIta87** [comment] 2024-10-29 16:41
I started modifying mods (for personal and hobby use) with Tohe. I had never used vscode. I managed to get a working mod without using the api key, deleting a file and making 2 small changes. Among other things, I also managed to extract the api key from the original dll file, but since it was not necessary, I immediately trashed it. So I confirm that the api key is not essential to make the mod work

**Comment by miniduikboot** [comment] 2024-10-29 20:05
> Btw it is possible that they just remove all the release dlls from github and only post their own build in discord or provide a download link somewhere else.
> In this way they dont have to make sure their build are 100% from source and they still dont lose the authoirty of the repo.

This is not acceptable according to section 6d of the GPL, which states that if you offer access to builds in a designated place, you need to offer access to the corresponding source in the same way through the same place at no further charge. So if you offer a download through Discord, you also have to post the source code in Discord.

> You can litterly make the public part of api accessible without a api key.
> I dont think there can be any use to require others to build with a api key.

If that removes the need to embed the API key into the binary, it would solve this concern, as then the corresponding source would be complete.

**Comment by 0xDrMoe** [comment] 2024-10-29 21:03
1.    Corresponding Source and API Key Requirement
The GNU GPL v3.0 defines “Corresponding Source” as all the source code necessary to run and modify the program, including scripts or configuration files required for these actions. TOHE provides all necessary source code to compile, install, and run the mod independently of the API key, which serves as an optional enhancement rather than a required element for basic functionality. In this context, the API key is specifically intended for accessing additional connectivity features, which are not core to the primary functionality of the mod.
To address your concern about functional equivalency, we are reviewing how to make the API key’s optional nature more transparent. We believe that this approach aligns with the GPL’s intent to ensure users have the freedom to run, modify, and distribute the software without dependency on proprietary components. Nevertheless, we are open to refining our documentation or code structure to clearly communicate any optional components and how they affect the mod’s capabilities.
    2.    Statement on Compilation with Dummy API Key
We understand that, at the time of the issue’s filing, TOHE required a placeholder or dummy API key for compilation. Since then, we have implemented changes to ensure that the mod can be compiled and run independently without the need for any API key, dummy or otherwise. We acknowledge that this was a gap in our initial implementation, and we have since resolved it to better align with GPL 3.0 requirements by ensuring complete, API-independent functionality at the base level.
As of this response, we are committed to ongoing reviews of TOHE’s GPL compliance to maintain transparency and ensure that any optional components remain strictly optional. We appreciate your feedback and are continually working to refine our approach to GPL compliance to meet both the letter and spirit of the license.

Thank you again for your questions. Please feel free to reach out to support@weareten.ca if there are additional concerns or if there’s anything specific you believe could further enhance our compliance with GPL standards.

**Comment by ThetaHalo** [comment] 2024-10-29 21:18
>    2.    Statement on Compilation with Dummy API Key
>    We understand that, at the time of the issue’s filing, TOHE required a placeholder or dummy API key for compilation. Since then, we have implemented changes to ensure that the mod can be compiled and run independently without the need for any API key, dummy or otherwise. We acknowledge that this was a gap in our initial implementation, and we have since resolved it to better align with GPL 3.0 requirements by ensuring complete, API-independent functionality at the base level.

just wondering, what exactly was done? all we can see is https://github.com/EnhancedNetwork/TownofHost-Enhanced/commit/a8b268a2854ac254909e17e59f0986d5c61c57fb being committed then being reverted 2 commits later?

**Comment by Tommy-XL** [comment] 2024-10-29 23:54
> just wondering, what exactly was done? all we can see is [a8b268a](https://github.com/EnhancedNetwork/TownofHost-Enhanced/commit/a8b268a2854ac254909e17e59f0986d5c61c57fb) being committed then being reverted 2 commits later in [4d9b343](https://github.com/EnhancedNetwork/TownofHost-Enhanced/commit/4d9b343eb1326c86b153cfc80aea6bef8b5eff59)?

Wtf, I didn't notice that the file was deleted

**Comment by Hyz-sui** [comment] 2024-10-30 00:35
This issue should not be closed until possible license violations are resolved.
You must provide the corresponding source in previous releases (as assets or otherwise).
You can disable the current API token before you do that if you want.

**Comment by Tommy-XL** [comment] 2024-10-30 03:38
> Wtf, I didn't notice that the file was deleted

I will return the file later

**Comment by NikoCat233** [comment] 2024-10-31 00:21
got a good idea
the mod caculates its file hash and use the hash as the api key

**Comment by 0xDrMoe** [comment] 2024-10-31 03:02
https://discord.com/channels/1094344790910455908/1109702972084068372/1301379711355715624 Please read this

**Comment by Hyz-sui** [comment] 2024-10-31 03:57
First of all, in general terms, it is not a good approach to embed the API token in resources.
Whoever got the binary can easily restore it in a simple way.
If you allow it, you do not need the API token. 
If not, you should not embed it in resources.
This means that this issue has two concerns: security and license compliance.

**Comment by NikoCat233** [comment] 2024-11-01 22:50
https://github.com/DouseDoused/TownofHost-Enhanced-Free-Prebuild-and-Dev-Acces
yeah there will be people who prefer to act instead of talking lol

**Comment by Tommy-XL** [comment] 2024-11-02 10:00
Personally, I see this solution:
Remove the API Token but the API itself will work as usual even if someone built it on the latest branch without a pop-up error saying that the API is not working

**Comment by Tommy-XL** [comment] 2024-11-02 10:06
The API itself, which limits something for those people who independently built on the latest branch in an open source code, is complete nonsense.

The API in my view should work as a helper function that allows you to add tag for players without waiting for the next version

**Comment by DouseDoused** [comment] 2024-11-02 22:49
Free full acces version has been updated to 2.1.0. Thanks for the developers for making an amazing mod, good people should handle the rest. this mod deserves more.

**Closed** 2024-11-02 23:42 UTC
Labels: Ask

**Comment by yurinakira** [comment] 2024-11-04 09:22
Why? Are you closing the issue without permission?
It's up to tukasa0001 to decide whether the issue is resolved or not.
